# This workflow builds, tests, and releases the modules.
name: Bruno Test

on:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test Bruno 
        uses: step-beyond/bruno-action@1.0.2
      
      
