# This workflow builds, tests, and releases the modules.
name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
jobs:
  # build library
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java_version: [ '17' ]
        os: [ 'ubuntu-latest' ]
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java_version }}
          distribution: 'temurin'
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Test with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: test testReport sonarqube --info
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Upload Test results
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # tag=v3
        with:
          name: ${{ matrix.os }}-${{ matrix.java_version }}-test-results
          path: |
            */build/test-results/**/*.xml
          retention-days: 7
  publish-test-results:
    name: "Publish Unit Tests Results"
    timeout-minutes: 60
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # tag=v3
        with:
          path: artifacts
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@a3caf02865c0604ad3dc1ecfcc5cdec9c41b7936 # tag=v2.1.0
        with:
          junit_files: "**/build/test-results/**/*.xml"
  semantic-release:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'
      - name: Install Semantic release
        run: |
          sudo npm install -g \
            semantic-release@20.1.0 \
            @semantic-release/git@10.0.1 \
            @semantic-release/release-notes-generator@10.0.3 \
            @semantic-release/github@8.0.7
      - name: Resolve publish app token
        id: app-token
        uses: getsentry/action-github-app-token@97c9e23528286821f97fba885c1b1123284b29cc # tag=v2.0.0
        with:
          app_id: ${{ secrets.GH_PUBLISH_APP_ID }}
          private_key: ${{ secrets.GH_PUBLISH_APP_PRIVATE_KEY }}

      - name: Release and Publish
        run: semantic-release
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}